@subdominio = frank-sjj9

###
GET http://{{subdominio}}.onrender.com/

###

GET http://{{subdominio}}.onrender.com/idat/codigo

###

GET http://{{subdominio}}.onrender.com/idat/nombre-completo

###
###
# 4: Listar cursos
GET http://{{subdominio}}.onrender.com/api/curso/listar/HTTP/1.1

###
# 5: Nuevo Curso
POST http://{{subdominio}}.onrender.com/api/curso/nuevo/HTTP/1.1
Content-Type: application/x-www-form-urlencoded

nombre=marketing
&creditos=2

###
# 6: Eliminar Curso
DELETE http://{{subdominio}}.onrender.com/api/curso/eliminar/HTTP/1.1
Content-Type: application/x-www-form-urlencoded

id=1